### PR TITLE
Add runtime and RSS memory as seen by RabbitMQ

### PR DESCRIPTION
**Pull request by essen**
This has not been built/tested yet, I lack the capacity to do it at the moment.

cc @gerhard

### CODE REVIEW

**Comment by deadtrickster** [comment]
So what is the plan there? do you want to wait for @gerhard's confirmation or I can go ahead and manually test it myself? Did you even figure out how to build this?

**Comment by essen** [comment]
We did just before the end of the day, and it works.

**Comment by deadtrickster** [comment]
:+1:

**Comment by essen** [comment]
Thanks for all the merges!

**Pull request merged**
