### PR TITLE
Fix ETS mappings rabbitmq core collector

### LINKED ISSUE #75: CRASH REPORT  with 0 neighbours crashed with reason: no function clause matching proplists:get_value(get, 0, undefined) line 215
rabbitmq about info

```
 {running_applications,
     [{prometheus_rabbitmq_exporter,
          "RabbitMQ Prometheus.io metrics exporter","3.7.2.5"},
      {rabbitmq_management,"RabbitMQ Management Console","3.7.12"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.7.12"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.7.12"},
      {rabbit,"RabbitMQ","3.7.12"},
      {amqp_client,"RabbitMQ AMQP Client","3.7.12"},
      {rabbit_common,
          "Modules shared by rabbitmq-server and rabbitmq-erlang-client",
          "3.7.12"},
      {os_mon,"CPO  CXC 138 46","2.4.7"},
      {cowboy,"Small, fast, modern HTTP server.","2.6.1"},
      {ranch,"Socket acceptor pool for TCP protocols.","1.7.1"},
      {ssl,"Erlang/OTP SSL application","9.1.2"},
      {public_key,"Public key infrastructure","1.6.4"},
      {asn1,"The Erlang ASN1 compiler version 5.0.8","5.0.8"},
      {prometheus_cowboy,[],"0.1.7"},
      {prometheus_httpd,"Prometheus.io inets httpd exporter","2.1.10"},
      {accept,"Accept header(s) for Erlang/Elixir","0.3.5"},
      {recon,"Diagnostic tools for production use","2.3.6"},
      {cowlib,"Support library for manipulating Web protocols.","2.7.0"},
      {crypto,"CRYPTO","4.4"},
      {sysmon_handler,"Rate-limiting system_monitor event handler","1.1.0"},
      {mnesia,"MNESIA  CXC 138 12","4.15.5"},
      {inets,"INETS  CXC 138 49","7.0.5"},
      {prometheus,"Prometheus.io client in Erlang","4.2.2"},
      {jsx,"a streaming, evented json parsing toolkit","2.9.0"},
      {xmerl,"XML parser","1.3.19"},
      {lager,"Erlang logging framework","3.6.5"},
      {goldrush,"Erlang event stream processor","0.1.9"},
      {compiler,"ERTS  CXC 138 10","7.3.1"},
      {syntax_tools,"Syntax tools","2.1.6"},
      {sasl,"SASL  CXC 138 11","3.3"},
      {stdlib,"ERTS  CXC 138 10","3.7.1"},
      {kernel,"ERTS  CXC 138 10","6.2"}]},
 {os,{unix,linux}},
 {erlang_version,
     "Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:128] [hipe]\n"},
```

but prometheus_rabbitmq_exporter crashed

```
[error] <0.4762.15> CRASH REPORT Process <0.4762.15> with 0 neighbours crashed with reason: no function clause matching proplists:get_value(get, 0, undefined) line 215

[error] <0.4761.15> Ranch listener rabbit_web_dispatch_sup_15672, connection process <0.4761.15>, stream 1 had its request process <0.4762.15> exit with reason function_clause and stacktrace [{proplists,get_value,[get,0,undefined],[{file,"proplists.erl"},{line,215}]},{prometheus_rabbitmq_core_metrics_collector,'-collect_metrics/2-lc$^0/1-0-',3,[{file,"src/collectors/prometheus_rabbitmq_core_metrics_collector.erl"},{line,177}]},{prometheus_model_helpers,create_mf,5,[{file,"/home/dead/Projects/rabbitmq/prometheus_rabbitmq_exporter/deps/prometheus/src/model/prometheus_model_helpers.erl"},{line,127}]},{prometheus_rabbitmq_core_metrics_collector,'-mf/3-lc$^2/1-1-',3,[{file,"src/collectors/prometheus_rabbitmq_core_metrics_collector.erl"},{line,169}]},{prometheus_rabbitmq_core_metrics_collector,'-collect_mf/2-lc$^0/1-0-',2,[{file,"src/collectors/prometheus_rabbitmq_core_metrics_collector.erl"},{line,153}]},{prometheus_rabbitmq_core_metrics_collector,collect_mf,2,[{file,"src/collectors/prometheus_rabbitmq_core_metrics_collector.erl"},{line,154}]},{prometheus_collector,collect_mf,3,[{file,"/home/dead/Projects/rabbitmq/prometheus_rabbitmq_exporter/deps/prometheus/src/prometheus_collector.erl"},{line,141}]},{prometheus_registry,'-collect/2-lc$^0/1-0-',3,[{file,"/home/dead/Projects/rabbitmq/prometheus_rabbitmq_exporter/deps/prometheus/src/prometheus_registry.erl"},{line,86}]}]
```

### PR DESCRIPTION
**Pull request by gerhard**
Fix metric mappings to ETS tables

In RabbitMQ v3.7.x, the following mappings were not valid and would
result in crashes when a produce/consumer would connect to RabbitMQ:

* connection_metrics
  * connection_recv_count, recv_count
  * connection_send_count, send_count

* channel_queue_metrics
  * channel_queue_get, get
  * channel_queue_get_no_ack, get_no_ack
  * channel_queue_deliver, deliver
  * channel_queue_deliver_no_ack, deliver_no_ack
  * channel_queue_redeliver, redeliver
  * channel_queue_ack, ack
  * channel_queue_get_empty, get_empty

The following metric was mapped incorrectly:

* connection_churn_metrics
  * 7, queue_deleted

There is more line churn in this commit than necessary. I was
re-formatting all metrics as I was going over all mappings. This
confirms that I've checked that all mappings are accurate.

I've tested manually against current v3.7.x branch via `make run-broker`
as well as rabbitmq:3.7.9 Docker image:

    make distclean

    make otp-21.2.5-build-context

      make /usr/local/bin/elixir
      apt update && apt install zip
      make ezs
      ^D

    make docker_build DOCKER_BASE_IMAGE=rabbitmq:3.7.9-management
    docker run -it -p 5672:5672 -p 15672:15672 deadtrickster/rabbitmq_prometheus:3.7

    cd ~/github.com/rabbitmq/rabbitmq-perf-test
    make run ARGS="-x 1 -y 1 -r 1"

    curl localhost:15672/api/metrics
    # NO CRASHES!

Fixes #75

cc @dcorbacho

### CODE REVIEW

**Comment by deadtrickster** [comment]
Awesome! version will be 3.7.9.1?

**Comment by gerhard** [comment]
Yes, 3.7.9.1 makes sense to me 👍🏻

**Comment by gerhard** [comment]
Before you cut a new release, let me share the Docker image which I've built locally. Maybe someone in #75 can confirm the fix before shipping.

**Comment by deadtrickster** [comment]
Thank you, Gerhard :-)

**Comment by gerhard** [comment]
@deadtrickster there is another PR like this one coming soon. Found other typos and incorrect descriptions. Going over everything like a🕵🏻‍♀️

**Comment by gerhard** [comment]
I didn't have time to PR this yet, but considering the amount of changes, it's safer to ask if it's worth putting one together: https://github.com/rabbitmq/rabbitmq-prometheus/commit/0057f07d1e870e9b2f000ad25865a89b09938c04#diff-fa0286c717bf744481489229d1e4ab5e. Notice that metric names have changed as well, as well as descriptions. Still want the PR?

**Comment by deadtrickster** [comment]
PRs are always welcome!

**Pull request merged**
