### PR TITLE
Build from source

### PR DESCRIPTION
**Pull request by gerhard**
Add `make ezs` so that we can build .ez files for all deps & plugin with a single command.

The resulting files will be placed in `./tmp`:

    ls -l tmp/
    total 992
    -rw-r--r--  1 gerhard  staff   12548 20 Feb 18:02 accept-0.3.4.ez
    -rw-r--r--  1 gerhard  staff  211232 20 Feb 18:02 prometheus-4.2.2.ez
    -rw-r--r--  1 gerhard  staff   14053 20 Feb 18:02 prometheus_cowboy-0.1.7.ez
    -rw-r--r--  1 gerhard  staff   21638 20 Feb 18:02 prometheus_httpd-2.1.10.ez
    -rw-r--r--  1 gerhard  staff   10708 20 Feb 18:02 prometheus_process_collector-1.4.0.ez
    -rw-r--r--  1 gerhard  staff  223943 20 Feb 18:02 prometheus_rabbitmq_exporter-3.7.20190220.ez

I've changed the version of this plugin to use the date for the patch part, feel free to change back if you disagree.

Notice that I've deleted the `prometheus_rabbitmq_exporter.app.src`, this is now generated by erlang.mk and dropped in `ebin/prometheus_rabbitmq_exporter.app` - does it look correct @deadtrickster?

Want to integrate with Docker & testing before merging.

This started as deadtrickster/prometheus_rabbitmq_exporter#63, see the discussion for more context.

### CODE REVIEW

**Comment by gerhard** [comment]
cc @dcorbacho

**Comment by tsloughter** [comment]
We prefer it if rebar3 is not committed to repos.

**Comment by deadtrickster** [comment]
I'm ok with the date, wondering why, though.

Does patched rebar3 archive work for you?

**Comment by gerhard** [comment]
> I'm ok with the date, wondering why, though.

The last release, prometheus_rabbitmq_exporter v3.7.2.4, indicates to me that it requires RabbitMQ v3.7.2. But does it work with RabbitMQ v3.7.12? What about RabbitMQ v3.7.1? By using a date, the indication is that it works with any RabbitMQ version published on or after this date. Is that a fair assumption to make? Can you think of a better approach?

Maybe @michaelklishin can suggest a better versioning schema. @dumbbell might also be able to help.

> Does patched rebar3 archive work for you?

No, it doesn't. 72ad2f2b442c1b7c58242d0b6f23af149213e52a uses `rebar3_archive_plugin` v0.0.2, as captured in `rebar.config`.

**Comment by deadtrickster** [comment]
> But does it work with RabbitMQ v3.7.12? What about RabbitMQ v3.7.1?

Hmm, I explained that in the README and issues, guess not clear, but - it works up to most recent. Really simple.

I just realized you tried to use rebar to build the plugin. Never tried that yet.

**Comment by gerhard** [comment]
@deadtrickster this is now ready for you. I've tested both `deadtrickster/rabbitmq_prometheus:3.7` & `deadtrickster/rabbitmq_prometheus:3.7-alpine` Docker image, `prometheus_rabbitmq_exporter` works as expected:

```
gmake docker_run

curl -svL -o /dev/null localhost:15672/api/metrics
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 15672 (#0)
> GET /api/metrics HTTP/1.1
> Host: localhost:15672
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< content-encoding: identity
< content-length: 144853
< content-type: text/plain; version=0.0.4
< date: Mon, 25 Feb 2019 17:05:48 GMT
< server: Cowboy
<
{ [16219 bytes data]
* Connection #0 to host localhost left intact
```

**Comment by deadtrickster** [comment]
Thanks, that's amazing. do you think

```
gmake docker_run

curl -svL -o /dev/null localhost:15672/api/metrics
```

is a good candidate for Travis/Circle?

**Comment by deadtrickster** [comment]
hmm, ln -h is bsd specific?

**Comment by gerhard** [comment]
> ```
> gmake docker_run
> 
> curl -svL -o /dev/null localhost:15672/api/metrics
> ```
> is a good candidate for Travis/Circle?

I almost added a make target that runs an acceptance test on both containers, but then didn't want to extend the PR too far. Yes, adding it to your CI of choice is a great idea. I would use curl's `--fail --fail-early` flags.

> hmm, ln -h is bsd specific?

Yes, it is. `-n` has the same effect & is cross-platform compatible:

```
LN(1)                     BSD General Commands Manual                    LN(1)

NAME
     link, ln -- make links

SYNOPSIS
     ln [-Ffhinsv] source_file [target_file]
     ln [-Ffhinsv] source_file ... target_dir

...
     -h    If the target_file or target_dir is a symbolic link, do not follow it.  This is most useful with the -f option, to replace a symlink which may point to a directory.

...

     -n    Same as -h, for compatibility with other ln implementations.
```

**Comment by deadtrickster** [comment]
so the sequence is `make ezs && make docker_build && make docker_push/run`. Or I'm missing the shortcut?

**Comment by gerhard** [comment]
Single command, multiple targets: make distclean up app ezs docker_build docker_run

**Comment by gerhard** [comment]
Will try on the Linux workstation later on today and add a few improvements. I've only made it work. Will make it right next & eventually make it fast 😉

**Comment by gerhard** [comment]
Picking this now on clean Linux: `docker run -it ubuntu`

**Comment by deadtrickster** [comment]
I added `make test`. It work, but I'm not sure I manager test container in the best possible way. Also, despite `@` it still produces some noise :-)

**Pull request merged**
